# Generated by Django 4.1.7 on 2023-05-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_id',
        ),
    ]
