# Generated by Django 4.1.7 on 2023-05-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exam_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.exam'),
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.IntegerField(unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.enroll'),
        ),
    ]
