# Generated by Django 4.1.7 on 2023-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_subject_exam_name_enroll_alter_studentresult_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(default=False, upload_to='profile_photos'),
        ),
    ]
