# Generated by Django 4.1.7 on 2023-05-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_adhar_no_remove_student_parents_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(default=False, upload_to='static/profile_photos'),
        ),
    ]
