# Generated by Django 4.1.7 on 2023-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_activity_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_file',
            field=models.ImageField(upload_to='static/activity'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.ImageField(upload_to='static/assignment'),
        ),
    ]
