# Generated by Django 4.1.7 on 2023-05-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_activity_activity_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assignment',
        ),
    ]
