# Generated by Django 4.1.7 on 2023-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_delete_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.TextField()),
                ('assignment_file', models.ImageField(upload_to='static/assignment')),
                ('enroll_no', models.IntegerField()),
            ],
        ),
    ]
