# Generated by Django 4.1.7 on 2023-05-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_studentresult_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='enroll_no',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
