# Generated by Django 4.1.7 on 2023-05-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_studentresult_enroll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_no', models.IntegerField()),
                ('year_day', models.IntegerField()),
                ('last_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available_size', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='static/products')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_link', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('event_banner', models.ImageField(blank=True, upload_to='')),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='enroll_no',
            field=models.IntegerField(default=0),
        ),
    ]
