# Generated by Django 4.1.7 on 2023-05-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_student_cource_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studying',
            field=models.BooleanField(default=1),
        ),
    ]
